extends: standard
plugins:
  - standard
  - promise
  - import
  - json

parserOptions:
  ecmaVersion: 7
  sourceType: "module"
  ecmaFeatures:
    impliedStrict: true

env:
  mocha: true
  node: true
  es6: true
  jest: true

parser: "babel-eslint"

rules:
  semi:
    - 2
    - "always"
  camelcase:
    - 2
    - properties: "always"
  comma-dangle:
    - 2
    - "only-multiline"
  indent:
    - 2
    - 2
  padded-blocks:
    - 2
    - "never"
#  operator-linebreak:
#    - 2
#    - "after"
#  space-before-function-paren:
#    - 2
#    - "never"
  space-in-parens:
    - 2
    - "never"
  no-tabs:
    0
  no-mixed-spaces-and-tabs:
    - 2
    - "smart-tabs"
  no-useless-escape:
    0
  no-unused-vars:
    2
settings:
  flowtype:
    onlyFilesWithFlowAnnotation:
      true
